### ISSUE TITLE
Unhandled promise rejection.

### ISSUE THREAD

**Issue by ArnoldasMk** [amitojsingh366/quizizz-hack#1]
hello, hack can't extract answers.

{20-11-19 12:11}pop-os:~/quiziz vega% ./quizizzHack-linux                              
Server running!
Go to http://localhost:6967
(node:509821) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/snapshot/quizizz-hack/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/quizizz-hack/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/quizizz-hack/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:509821) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:509821) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Arsalaan-Alam** [comment]
Yeah same happened bruh. It doesnt work

**Comment by ArnoldasMk** [comment]
I think they patched everything.

**Comment by amitojsingh366** [comment]
> I think they patched everything.

Yup that's exactly what happened. Live quiz's can't be hacked anymore.
You can still get answers to all other quiz's tho.....

**Comment by Arsalaan-Alam** [comment]
Hey, could you please tell me how to hack other quizzes. How can I get their id. Pls tell

**Comment by amitojsingh366** [comment]
@arsalaan12 The other quiz's ids can be found by looking at the URL as shown in the screenshot below
<img width="400" alt="Screen Shot 2020-11-21 at 10 48 48 AM" src="https://user-images.githubusercontent.com/35400192/99870871-59dc9480-2be7-11eb-94f4-9734a2fe98e7.png">

**Comment by Arsalaan-Alam** [comment]
Yeah great. Thanks, man

**Comment by ItsVendetta** [comment]
> @arsalaan12 The other quiz's ids can be found by looking at the URL as shown in the screenshot below
> <img alt="Screen Shot 2020-11-21 at 10 48 48 AM" width="400" src="https://user-images.githubusercontent.com/35400192/99870871-59dc9480-2be7-11eb-94f4-9734a2fe98e7.png">

did this also get patched or am I looking in the wrong place? 
![image](https://user-images.githubusercontent.com/74819456/99876483-60cbcd00-2c10-11eb-942a-07d63c764e4a.png)
