### ISSUE TITLE
How can I get answers from link like "https://quizizz.com/join/quiz/SOME_DIGITS/start?studentShare=true"

### ISSUE THREAD

**Issue by S1riyS** [amitojsingh366/quizizz-hack#2]
This method works only with link like https://quizizz.com/join/quiz/SOME_DIGITS/start. But I need to get answers from a different type of link

**Comment by amitojsingh366** [comment]
As mentioned in #1 all of the ways to get live answers has been patched. ie Other links will not work as quizizz issued a patch....

**Comment by S1riyS** [comment]
So sad(

**Comment by Arsalaan-Alam** [comment]
No a person actually hacked it. We just need to know how to extract quizizz id. All will work

**Comment by Arsalaan-Alam** [comment]
Could you tell me how to?

**Comment by amitojsingh366** [comment]
> No a person actually hacked it. We just need to know how to extract quizizz id. All will work

Yes I am aware that you can hack and get the quiz ID however it is an extremely difficult task to do (as I tried it) and will require a lot of time. Not to mention the legalities that one would have to face.

**Comment by Arsalaan-Alam** [comment]
Okay, bro. Are you on discord. If yes please tell your id. We could combine and make a hack for quizizz. Check out qzlr.eu. They are actually charging 1 euro for 3 times answers.

**Comment by Arsalaan-Alam** [comment]
Are you able to extract the quiz id?
I took it out. But I couldn't decode it
