### ISSUE TITLE
How to find a real and working quizID from a live quiz

### ISSUE THREAD

**Issue by cohzily** [amitojsingh366/quizizz-hack#4]
to start off, i know this isnt an 'issue' but i really just made this account to spread this info i found and i really dont know how to use the pull requests tab. 2nd: yes, this does mean you can find answers on a live quiz!
NOTE: I MADE THE MISTAKE OF NOT USING AN ACCOUNT ON THE HOST USER, I WILL TRY TO FIND ANOTHER METHOD BUT S OF RIGHT NOW THIS PROBABLY WOULDNT WORK FOR YOU

Steps:

1) join the quizizz game with a link like quizizz.com/join?gc=GAMECODE but *DO NOT CLICK START STAY IN THE NAME ENTER SCREEN*

2) ctrl + shift + i, go to network tab then ctrl + r

3) ctrl + f and search for 'v4', you should find a "....com/api/main/v4/students highlighted in green. click it

4) in the small window on the right change "preview" to "response" and copy the entire response to a text editor to make it easier

5) right at the start you will find {"items":[{"_id":"bunch of letters and numbers" copy the letters and numbers

6) go to quizizz.com/admin/quiz/PASTEHERE/startV4 you should be at the admin screen

7) ctrl + shift + i, network tab, ctrl r, then instead of ctrl f and searching, you want to order the network requests by name, and look for a request called "*the-id-from-step-5*?_=numbers" click on it, go to response, and copy it to a text editor

8) ctrl f and search for "quizID" you should find a match and the text to the right of it is the correct quizid that you put in on localhost:6967

enjoy your live quiz answers :)

**Comment by amitojsingh366** [comment]
Ok, I've tested this and unfortunately, it doesn't work... At least for the quiz, I was trying on it wasn't working. I think quizzes have some authentication on who can start the particular quiz as I got a "User not authorized" response.
Below is the attached screenshot that shows it
<img width="1001" alt="Screen Shot 2020-11-26 at 6 03 26 PM" src="https://user-images.githubusercontent.com/35400192/100366271-b0940500-3011-11eb-898c-a8ef6c9372da.png">
I tried following all the steps you've mentioned and if I'm wrong and this actually does work ill like to integrate it within the main app itself.
[this](https://quizizz.com/join?gc=636061) was the quiz I've tried your method on

**Comment by mdzk** [comment]
{"success":false,"error":"user.ACCESS_NOT_ALLOWED","message":"User not authorized"}

**Comment by CrosserX** [comment]
[quiz id.txt](https://github.com/amitojsingh366/quizizz-hack/files/5622834/quiz.id.txt)
its an instruction on how to get the quiz id

**Comment by CrosserX** [comment]
![2020-12-01](https://user-images.githubusercontent.com/72391942/100748374-d5271d00-3415-11eb-94b0-1496d2ddc04f.png)
it should look like that

**Comment by Myxy1** [comment]
@CrosserX so is it work for you?

**Comment by CrosserX** [comment]
yea

**Comment by CrosserX** [comment]
@Myxy1 does it not work for you?

**Comment by Myxy1** [comment]
@CrosserX yes
please can you make a step by step move with pictures how to get quiz id?

**Comment by Myxy1** [comment]
@CrosserX the practise mode work for me but the online mode not..

**Comment by CrosserX** [comment]
> @CrosserX yes
> please can you make a step by step move with pictures how to get quiz id?

ok, maybe tommorow i'm feeling kinda lazy today

**Comment by CrosserX** [comment]
> @CrosserX the practise mode work for me but the online mode not..

well i found the tutorial when i was browsing in tor, by online mode do you mean live games?

**Comment by CrosserX** [comment]
if it is really live games idk what's the problem, i haven't try it on live games

**Comment by Myxy1** [comment]
yea i mean live game..

**Comment by Myxy1** [comment]
at 10o clock i have an exam xd

**Comment by CrosserX** [comment]
i'm going to have a final semester test next week XD

**Comment by Myxy1** [comment]
Waooo 👍 
Dude :DD i need help now :( :'D

**Comment by CrosserX** [comment]
> yea i mean live game..

ok let me try it on live game, real quick

**Comment by CrosserX** [comment]
well, so i tried it but then i realized that i don't have any live games from my teacher, let me try it when my teacher give me a live game. ok?

**Comment by Myxy1** [comment]
i can give you a live code

**Comment by CrosserX** [comment]
ok then

**Comment by CrosserX** [comment]
let me try it on that one

**Comment by Myxy1** [comment]
7780305

**Comment by Myxy1** [comment]
there are only two questions, just test it

**Comment by CrosserX** [comment]
found it

**Comment by CrosserX** [comment]
![2020-12-02 (1)](https://user-images.githubusercontent.com/72391942/100845955-85e1fa80-34b0-11eb-9127-ba8d9808b19e.png)
![2020-12-02 (3)](https://user-images.githubusercontent.com/72391942/100845981-8e3a3580-34b0-11eb-978d-ba4eabd748b7.png)

**Comment by Myxy1** [comment]
WAO

**Comment by CrosserX** [comment]
wait

**Comment by CrosserX** [comment]
i didn't change my name

**Comment by CrosserX** [comment]
loooool

**Comment by Myxy1** [comment]
So?

**Comment by CrosserX** [comment]
nah, nothing

**Comment by CrosserX** [comment]
let me send it again

**Comment by Myxy1** [comment]
It's working right?

**Comment by CrosserX** [comment]
![2020-12-02 (4)](https://user-images.githubusercontent.com/72391942/100846254-e07b5680-34b0-11eb-8a84-1975e4d6f20e.png)
![2020-12-02 (3)](https://user-images.githubusercontent.com/72391942/100846287-e7a26480-34b0-11eb-8f69-1a7175041d8b.png)

**Comment by CrosserX** [comment]
yeah

**Comment by CrosserX** [comment]
it's working

**Comment by Myxy1** [comment]
Thanks dude!

**Comment by CrosserX** [comment]
no problem

**Comment by CrosserX** [comment]
@amitojsingh366 is the hack still available?

**Comment by CrosserX** [comment]
quizizz just updated a few weeks ago, i think

**Comment by Myxy1** [comment]
@CrosserX yea i found the quizz id but the hack not working :/

**Comment by Myxy1** [comment]
yea i think it's patched :|

**Comment by amitojsingh366** [comment]
Well as I mentioned in [README.md](https://github.com/amitojsingh366/quizizz-hack/blob/main/README.md) the hack was patched fairly quickly but the creator of this issue @cohzily told that we can get the real ids *(which got me surprised cuz I spent hours looking for a way to do it)*. If somehow you can get the real id not the masked one you can still use my hack, tho all ways to get the real id have been patched. The way @CrosserX mentions only shows the masked id and that's why it won't work... And @Myxy1 a practice quiz doesn't mask the id thus my hack still works....

**Comment by CrosserX** [comment]
ok thx for the info

**Comment by xxczaki** [comment]
I can confirm, that the method from @cohzily is working for public live quizzes. However, I don't think it will work for private ones, as now they require a login and if you are not the creator, you will be shown with the "request access" button.

**Comment by Myxy1** [comment]
I just found a js script what is show the actually questions :D and it's work in live game 
if you want to this js script ask me

**Comment by franekxtb** [comment]
> I just found a js script what is show the actually questions :D and it's work in live game
> if you want to this js script ask me

Hi, does it still work ? If so, would you mind sharing a link ?

**Comment by naaskel** [comment]
> I just found a js script what is show the actually questions :D and it's work in live game
> if you want to this js script ask me

wanna share?

**Comment by Myxy1** [comment]
@Natqo @FilipLitwora sry, the script code is now not working, after a few days they patched

**Comment by uc183** [comment]
the hack still available?

**Comment by amitojsingh366** [comment]
As the way first described in this issue to gain the quiz ID does not work anymore I will be closing this issue.
Feel free to open up a new issue if required.
Depending on the circumstances I may/may not work on a new version of this hack
